# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/parser-7.22.14" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.22.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.22.14.tgz";
        sha512 = "1KucTHgOvaw/LzCVrEOAyXkr9rQlp0A1HiHRYnSUE9dmb8PvPW7o5sscg+5169r54n3vGlbx6GevTE/Iw/P3AQ==";
      };
    };
    "@jridgewell/sourcemap-codec-1.4.15" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.4.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.4.15.tgz";
        sha512 = "eF2rxCRulEKXHTRiDrDy6erMYWqNw4LPdQ8UQA4huuxaQsVeRPFl2oM8oDGxMFhJUWZf9McpLtJasDDZb/Bpeg==";
      };
    };
    "@tauri-apps/api-1.4.0" = {
      name = "_at_tauri-apps_slash_api";
      packageName = "@tauri-apps/api";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tauri-apps/api/-/api-1.4.0.tgz";
        sha512 = "Jd6HPoTM1PZSFIzq7FB8VmMu3qSSyo/3lSwLpoapW+lQ41CL5Dow2KryLg+gyazA/58DRWI9vu/XpEeHK4uMdw==";
      };
    };
    "@vue/compiler-core-3.3.4" = {
      name = "_at_vue_slash_compiler-core";
      packageName = "@vue/compiler-core";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-core/-/compiler-core-3.3.4.tgz";
        sha512 = "cquyDNvZ6jTbf/+x+AgM2Arrp6G4Dzbb0R64jiG804HRMfRiFXWI6kqUVqZ6ZR0bQhIoQjB4+2bhNtVwndW15g==";
      };
    };
    "@vue/compiler-dom-3.3.4" = {
      name = "_at_vue_slash_compiler-dom";
      packageName = "@vue/compiler-dom";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-dom/-/compiler-dom-3.3.4.tgz";
        sha512 = "wyM+OjOVpuUukIq6p5+nwHYtj9cFroz9cwkfmP9O1nzH68BenTTv0u7/ndggT8cIQlnBeOo6sUT/gvHcIkLA5w==";
      };
    };
    "@vue/compiler-sfc-3.3.4" = {
      name = "_at_vue_slash_compiler-sfc";
      packageName = "@vue/compiler-sfc";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-sfc/-/compiler-sfc-3.3.4.tgz";
        sha512 = "6y/d8uw+5TkCuzBkgLS0v3lSM3hJDntFEiUORM11pQ/hKvkhSKZrXW6i69UyXlJQisJxuUEJKAWEqWbWsLeNKQ==";
      };
    };
    "@vue/compiler-ssr-3.3.4" = {
      name = "_at_vue_slash_compiler-ssr";
      packageName = "@vue/compiler-ssr";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-ssr/-/compiler-ssr-3.3.4.tgz";
        sha512 = "m0v6oKpup2nMSehwA6Uuu+j+wEwcy7QmwMkVNVfrV9P2qE5KshC6RwOCq8fjGS/Eak/uNb8AaWekfiXxbBB6gQ==";
      };
    };
    "@vue/reactivity-3.3.4" = {
      name = "_at_vue_slash_reactivity";
      packageName = "@vue/reactivity";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/reactivity/-/reactivity-3.3.4.tgz";
        sha512 = "kLTDLwd0B1jG08NBF3R5rqULtv/f8x3rOFByTDz4J53ttIQEDmALqKqXY0J+XQeN0aV2FBxY8nJDf88yvOPAqQ==";
      };
    };
    "@vue/reactivity-transform-3.3.4" = {
      name = "_at_vue_slash_reactivity-transform";
      packageName = "@vue/reactivity-transform";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/reactivity-transform/-/reactivity-transform-3.3.4.tgz";
        sha512 = "MXgwjako4nu5WFLAjpBnCj/ieqcjE2aJBINUNQzkZQfzIZA4xn+0fV1tIYBJvvva3N3OvKGofRLvQIwEQPpaXw==";
      };
    };
    "@vue/runtime-core-3.3.4" = {
      name = "_at_vue_slash_runtime-core";
      packageName = "@vue/runtime-core";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/runtime-core/-/runtime-core-3.3.4.tgz";
        sha512 = "R+bqxMN6pWO7zGI4OMlmvePOdP2c93GsHFM/siJI7O2nxFRzj55pLwkpCedEY+bTMgp5miZ8CxfIZo3S+gFqvA==";
      };
    };
    "@vue/runtime-dom-3.3.4" = {
      name = "_at_vue_slash_runtime-dom";
      packageName = "@vue/runtime-dom";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/runtime-dom/-/runtime-dom-3.3.4.tgz";
        sha512 = "Aj5bTJ3u5sFsUckRghsNjVTtxZQ1OyMWCr5dZRAPijF/0Vy4xEoRCwLyHXcj4D0UFbJ4lbx3gPTgg06K/GnPnQ==";
      };
    };
    "@vue/server-renderer-3.3.4" = {
      name = "_at_vue_slash_server-renderer";
      packageName = "@vue/server-renderer";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/server-renderer/-/server-renderer-3.3.4.tgz";
        sha512 = "Q6jDDzR23ViIb67v+vM1Dqntu+HUexQcsWKhhQa4ARVzxOY2HbC7QRW/ggkDBd5BU+uM1sV6XOAP0b216o34JQ==";
      };
    };
    "@vue/shared-3.3.4" = {
      name = "_at_vue_slash_shared";
      packageName = "@vue/shared";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/shared/-/shared-3.3.4.tgz";
        sha512 = "7OjdcV8vQ74eiz1TZLzZP4JwqM5fA94K6yntPS5Z25r9HDuGNzaGdgvwKYq6S+MxwF0TFRwe50fIR/MYnakdkQ==";
      };
    };
    "ansi-regex-4.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-4.1.1.tgz";
        sha512 = "ILlv4k/3f6vfQ4OoP2AGvirOktlQ98ZEL1k9FaQjxa3L1abBgbuTDAdPOpvbGncC0BTVQrl+OM8xZGK6tWXt7g==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "axios-0.23.0" = {
      name = "axios";
      packageName = "axios";
      version = "0.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/axios/-/axios-0.23.0.tgz";
        sha512 = "NmvAE4i0YAv5cKq8zlDoPd1VLKAqX5oLuZKs8xkJa4qi6RGn0uhCYFjWtHHC9EM/MwOwYWOs53W+V0aqEXq1sg==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "bl-1.2.3" = {
      name = "bl";
      packageName = "bl";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.2.3.tgz";
        sha512 = "pvcNpa0UU69UT341rO6AYy4FVAIkUHuZXRIWbq+zHnsVcRzDDjIAhGuuYoi0d//cwIwtt4pkpKycWEfjdV+vww==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "buffer-5.7.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.7.1.tgz";
        sha512 = "EHcyIPBQ4BSGlvjB16k5KgAJ27CIsHY/2JBmCRReo48y9rQ3MaUzWX3KVlBa4U7MyX02HdVj0K7C3WaB3ju7FQ==";
      };
    };
    "buffer-alloc-1.2.0" = {
      name = "buffer-alloc";
      packageName = "buffer-alloc";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-alloc/-/buffer-alloc-1.2.0.tgz";
        sha512 = "CFsHQgjtW1UChdXgbyJGtnm+O/uLQeZdtbDo8mfUgYXCHSM1wgrVxXm6bSyrUuErEb+4sYVGCzASBRot7zyrow==";
      };
    };
    "buffer-alloc-unsafe-1.1.0" = {
      name = "buffer-alloc-unsafe";
      packageName = "buffer-alloc-unsafe";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-alloc-unsafe/-/buffer-alloc-unsafe-1.1.0.tgz";
        sha512 = "TEM2iMIEQdJ2yjPJoSIsldnleVaAk1oW3DBVUykyOLsEsFmEc9kn+SFFPz+gl54KQNxlDnAwCXosOS9Okx2xAg==";
      };
    };
    "buffer-crc32-0.2.13" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz";
        sha512 = "VO9Ht/+p3SN7SKWqcrgEzjGbRSJYTx+Q1pTQC0wrWqHx0vpJraQ6GtHx8tvcg1rlK1byhU5gccxgOgj7B0TDkQ==";
      };
    };
    "buffer-fill-1.0.0" = {
      name = "buffer-fill";
      packageName = "buffer-fill";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-fill/-/buffer-fill-1.0.0.tgz";
        sha512 = "T7zexNBwiiaCOGDg9xNX9PBmjrubblRkENuptryuI64URkXDFum9il/JGL8Lm8wYfAXpredVXXZz7eMHilimiQ==";
      };
    };
    "capture-stack-trace-1.0.2" = {
      name = "capture-stack-trace";
      packageName = "capture-stack-trace";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/capture-stack-trace/-/capture-stack-trace-1.0.2.tgz";
        sha512 = "X/WM2UQs6VMHUtjUDnZTRI+i1crWteJySFzr9UpGoQa4WQffXVTTXuekjl7TjZRlcF2XfjgITT0HxZ9RnxeT0w==";
      };
    };
    "cargo-cli-0.0.7" = {
      name = "cargo-cli";
      packageName = "cargo-cli";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/cargo-cli/-/cargo-cli-0.0.7.tgz";
        sha512 = "TWfaBks0OQZ8/ewY6WpUnmicM6sX0e05x3lZnliOSSufLxQzAIYc+xR8N8Y9mZ7G0dcb3YybP6nd3lHa/57+xw==";
      };
    };
    "caw-2.0.1" = {
      name = "caw";
      packageName = "caw";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/caw/-/caw-2.0.1.tgz";
        sha512 = "Cg8/ZSBEa8ZVY9HspcGUYaK63d/bN7rqS3CYCzEGUxuYv6UlmcjzDUz2fCFFHyTvUW5Pk0I+3hkA3iXlIj6guA==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "cli-cursor-2.1.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-2.1.0.tgz";
        sha512 = "8lgKz8LmCRYZZQDpRyT2m5rKJ08TnU4tR9FFFW2rxpxR1FzWi4PQ/NfyODchAatHaUgnSPVcx/R5w6NuTBzFiw==";
      };
    };
    "cli-spinners-1.3.1" = {
      name = "cli-spinners";
      packageName = "cli-spinners";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-spinners/-/cli-spinners-1.3.1.tgz";
        sha512 = "1QL4544moEsDVH9T/l6Cemov/37iv1RtoKf7NJ04A60+4MREXNfx/QvavbH6QoGdsD4N4Mwy49cmaINR/o2mdg==";
      };
    };
    "cli-spinners-2.9.0" = {
      name = "cli-spinners";
      packageName = "cli-spinners";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-spinners/-/cli-spinners-2.9.0.tgz";
        sha512 = "4/aL9X3Wh0yiMQlE+eeRhWP6vclO3QRtw1JHKIT0FFUs5FjpFmESqtMvYZ0+lbzBw900b95mS0hohy+qn2VK/g==";
      };
    };
    "clone-1.0.4" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.4.tgz";
        sha512 = "JQHZ2QMW6l3aH/j6xCqQThY/9OH4D/9ls34cgkUBiEeocRTU04tHfKPBsUK1PqZCUQM7GiA0IIXJSuXHI64Kbg==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "config-chain-1.1.13" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.13.tgz";
        sha512 = "qj+f8APARXHrM0hraqXYb2/bOVSV4PvJQlNZ/DVj0QrmNM2q2euizkeuVckQ57J+W0mRH6Hvi+k50M4Jul2VRQ==";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "create-error-class-3.0.2" = {
      name = "create-error-class";
      packageName = "create-error-class";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-error-class/-/create-error-class-3.0.2.tgz";
        sha512 = "gYTKKexFO3kh200H1Nit76sRwRtOY32vQd3jpAQKpLtZqyNsSQNfI4N7o3eP2wUjV35pTWKRYqFUDBvUha/Pkw==";
      };
    };
    "cron-1.8.2" = {
      name = "cron";
      packageName = "cron";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cron/-/cron-1.8.2.tgz";
        sha512 = "Gk2c4y6xKEO8FSAUTklqtfSr7oTq0CiPQeLBG5Fl0qoXpZyMcj1SG59YL+hqq04bu6/IuEA7lMkYDAplQNKkyg==";
      };
    };
    "csstype-3.1.2" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.1.2.tgz";
        sha512 = "I7K1Uu0MBPzaFKg4nI5Q7Vs2t+3gWWW648spaF+Rg7pI9ds18Ugn+lvg4SHczUdKlHI5LWBXyqfS8+DufyBsgQ==";
      };
    };
    "decompress-4.2.1" = {
      name = "decompress";
      packageName = "decompress";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress/-/decompress-4.2.1.tgz";
        sha512 = "e48kc2IjU+2Zw8cTb6VZcJQ3lgVbS4uuB1TfCHbiZIP/haNXm+SVyhu+87jts5/3ROpd82GSVCoNs/z8l4ZOaQ==";
      };
    };
    "decompress-tar-4.1.1" = {
      name = "decompress-tar";
      packageName = "decompress-tar";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-tar/-/decompress-tar-4.1.1.tgz";
        sha512 = "JdJMaCrGpB5fESVyxwpCx4Jdj2AagLmv3y58Qy4GE6HMVjWz1FeVQk1Ct4Kye7PftcdOo/7U7UKzYBJgqnGeUQ==";
      };
    };
    "decompress-tarbz2-4.1.1" = {
      name = "decompress-tarbz2";
      packageName = "decompress-tarbz2";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-tarbz2/-/decompress-tarbz2-4.1.1.tgz";
        sha512 = "s88xLzf1r81ICXLAVQVzaN6ZmX4A6U4z2nMbOwobxkLoIIfjVMBg7TeguTUXkKeXni795B6y5rnvDw7rxhAq9A==";
      };
    };
    "decompress-targz-4.1.1" = {
      name = "decompress-targz";
      packageName = "decompress-targz";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-targz/-/decompress-targz-4.1.1.tgz";
        sha512 = "4z81Znfr6chWnRDNfFNqLwPvm4db3WuZkqV+UgXQzSngG3CEKdBkw5jrv3axjjL96glyiiKjsxJG3X6WBZwX3w==";
      };
    };
    "decompress-unzip-4.0.1" = {
      name = "decompress-unzip";
      packageName = "decompress-unzip";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-unzip/-/decompress-unzip-4.0.1.tgz";
        sha512 = "1fqeluvxgnn86MOh66u8FjbtJpAFv5wgCT9Iw8rcBqQcCo5tO8eiJw7NNTrvt9n4CRBVq7CstiS922oPgyGLrw==";
      };
    };
    "defaults-1.0.4" = {
      name = "defaults";
      packageName = "defaults";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/defaults/-/defaults-1.0.4.tgz";
        sha512 = "eFuaLoy/Rxalv2kr+lqMlUnrDWV+3j4pljOIJgLIhI058IQfWJ7vXhyEIHu+HtC738klGALYxOKDO0bQP3tg8A==";
      };
    };
    "dexie-3.2.4" = {
      name = "dexie";
      packageName = "dexie";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/dexie/-/dexie-3.2.4.tgz";
        sha512 = "VKoTQRSv7+RnffpOJ3Dh6ozknBqzWw/F3iqMdsZg958R0AS8AnY9x9d1lbwENr0gzeGJHXKcGhAMRaqys6SxqA==";
      };
    };
    "download-5.0.3" = {
      name = "download";
      packageName = "download";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/download/-/download-5.0.3.tgz";
        sha512 = "rE0V29BV5FyylK3Uw5hmP90TBuwGHAqPYfaRHW/VHsKe9Xqi7RACVg0k0FokeE+MTWr9mtUy75GyszRACiD3Ow==";
      };
    };
    "download-git-repo-1.1.0" = {
      name = "download-git-repo";
      packageName = "download-git-repo";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/download-git-repo/-/download-git-repo-1.1.0.tgz";
        sha512 = "yXcCvhkPKmq5M2cQXss6Qbig+LZnzRIT40XCYm/QCRnJaPG867StB1qnsBLxOGrPH1YEIRWW2gJq7LLMyw+NmA==";
      };
    };
    "duplexer3-0.1.5" = {
      name = "duplexer3";
      packageName = "duplexer3";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer3/-/duplexer3-0.1.5.tgz";
        sha512 = "1A8za6ws41LQgv9HrE/66jyC5yuSjQ3L/KOpFtoBilsAK2iA2wuS5rTt1OCzIvtS2V7nVmedsUU+DGRcjBmOYA==";
      };
    };
    "end-of-stream-1.4.4" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz";
        sha512 = "+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "fd-slicer-1.1.0" = {
      name = "fd-slicer";
      packageName = "fd-slicer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fd-slicer/-/fd-slicer-1.1.0.tgz";
        sha512 = "cE1qsB/VwyQozZ+q1dGxR8LBYNZeofhEdUNGSMbQD3Gw2lAzX9Zb3uIU6Ebc/Fmyjo9AWWfnn0AUCHqtevs/8g==";
      };
    };
    "file-type-3.9.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "3.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-3.9.0.tgz";
        sha512 = "RLoqTXE8/vPmMuTI88DAzhMYC99I8BWv7zYP4A1puo5HIjEJ5EX48ighy4ZyKMG9EDXxBgW6e++cn7d1xuFghA==";
      };
    };
    "file-type-5.2.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-5.2.0.tgz";
        sha512 = "Iq1nJ6D2+yIO4c8HHg4fyVb8mAJieo1Oloy1mLLaB2PvezNedhBVm+QU7g0qM42aiMbRXTxKKwGD17rjKNJYVQ==";
      };
    };
    "file-type-6.2.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-6.2.0.tgz";
        sha512 = "YPcTBDV+2Tm0VqjybVd32MHdlEGAtuxS3VAYsumFokDSMG+ROT5wawGlnHDoz7bfMcMDt9hxuXvXwoKUx2fkOg==";
      };
    };
    "filename-reserved-regex-2.0.0" = {
      name = "filename-reserved-regex";
      packageName = "filename-reserved-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filename-reserved-regex/-/filename-reserved-regex-2.0.0.tgz";
        sha512 = "lc1bnsSr4L4Bdif8Xb/qrtokGbq5zlsms/CYH8PP+WtCkGNF65DPiQY8vG3SakEdRn8Dlnm+gW/qWKKjS5sZzQ==";
      };
    };
    "filenamify-2.1.0" = {
      name = "filenamify";
      packageName = "filenamify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filenamify/-/filenamify-2.1.0.tgz";
        sha512 = "ICw7NTT6RsDp2rnYKVd8Fu4cr6ITzGy3+u4vUujPkabyaz+03F24NWEX7fs5fp+kBonlaqPH8fAO2NM+SXt/JA==";
      };
    };
    "follow-redirects-1.15.2" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.15.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.2.tgz";
        sha512 = "VQLG33o04KaQ8uYi2tVNbdrWp1QWxNNea+nmIB4EVM28v0hmP17z7aG1+wAkNzVq4KeXTq3221ye5qTJP91JwA==";
      };
    };
    "fs-constants-1.0.0" = {
      name = "fs-constants";
      packageName = "fs-constants";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-constants/-/fs-constants-1.0.0.tgz";
        sha512 = "y6OAwoSIf7FyjMIv94u+b5rdheZEjzR63GTyZJm5qh4Bi+2YgwLCcI/fPFZkL5PSixOt6ZNKm+w+Hfp/Bciwow==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "get-proxy-2.1.0" = {
      name = "get-proxy";
      packageName = "get-proxy";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-proxy/-/get-proxy-2.1.0.tgz";
        sha512 = "zmZIaQTWnNQb4R4fJUEp/FC51eZsc6EkErspy3xtIYStaq8EB/hDIWipxsal+E8rz0qD7f2sL/NA9Xee4RInJw==";
      };
    };
    "get-stream-2.3.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-2.3.1.tgz";
        sha512 = "AUGhbbemXxrZJRD5cDvKtQxLuYaIbNtDTK8YqupCI393Q2KSTreEsLUN3ZxAWFGiKTzL6nKuzfcIvieflUX9qA==";
      };
    };
    "get-stream-3.0.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-3.0.0.tgz";
        sha512 = "GlhdIUuVakc8SJ6kK0zAFbiGzRFzNnY4jUuEbV9UROo4Y+0Ny4fjvcZFVTeDA4odpFyOQzaw6hXukJSq/f28sQ==";
      };
    };
    "git-clone-0.1.0" = {
      name = "git-clone";
      packageName = "git-clone";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/git-clone/-/git-clone-0.1.0.tgz";
        sha512 = "zs9rlfa7HyaJAKG9o+V7C6qfMzyc+tb1IIXdUFcOBcR1U7siKy/uPdauLlrH1mc0vOgUwIv4BF+QxPiiTYz3Rw==";
      };
    };
    "glob-7.2.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.3.tgz";
        sha512 = "nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==";
      };
    };
    "got-6.7.1" = {
      name = "got";
      packageName = "got";
      version = "6.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-6.7.1.tgz";
        sha512 = "Y/K3EDuiQN9rTZhBvPRWMLXIKdeD1Rj0nzunfoi0Yyn5WBEbzxXKU9Ub2X41oZBagVWOBU3MuDonFMgPWQFnwg==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha512 = "sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==";
      };
    };
    "has-symbol-support-x-1.4.2" = {
      name = "has-symbol-support-x";
      packageName = "has-symbol-support-x";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbol-support-x/-/has-symbol-support-x-1.4.2.tgz";
        sha512 = "3ToOva++HaW+eCpgqZrCfN51IPB+7bJNVT6CUATzueB5Heb8o6Nam0V3HG5dlDvZU1Gn5QLcbahiKw/XVk5JJw==";
      };
    };
    "has-to-string-tag-x-1.4.1" = {
      name = "has-to-string-tag-x";
      packageName = "has-to-string-tag-x";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-to-string-tag-x/-/has-to-string-tag-x-1.4.1.tgz";
        sha512 = "vdbKfmw+3LoOYVr+mtxHaX5a96+0f3DljYd8JOqvOLsf5mw2Otda2qCDT9qRqLAhrjyQ0h7ual5nOiASpsGNFw==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "is-natural-number-4.0.1" = {
      name = "is-natural-number";
      packageName = "is-natural-number";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-natural-number/-/is-natural-number-4.0.1.tgz";
        sha512 = "Y4LTamMe0DDQIIAlaer9eKebAlDSV6huy+TWhJVPlzZh2o4tRP5SQWFlLn5N0To4mDD22/qdOq+veo1cSISLgQ==";
      };
    };
    "is-object-1.0.2" = {
      name = "is-object";
      packageName = "is-object";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-object/-/is-object-1.0.2.tgz";
        sha512 = "2rRIahhZr2UWb45fIOuvZGpFtz0TyOZLf32KxBbSoUCeZR495zCKlWUKKUByk3geS2eAs7ZAABt0Y/Rx0GiQGA==";
      };
    };
    "is-redirect-1.0.0" = {
      name = "is-redirect";
      packageName = "is-redirect";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-redirect/-/is-redirect-1.0.0.tgz";
        sha512 = "cr/SlUEe5zOGmzvj9bUyC4LVvkNVAXu4GytXLNMr1pny+a65MpQ9IJzFHD5vi7FyJgb4qt27+eS3TuQnqB+RQw==";
      };
    };
    "is-retry-allowed-1.2.0" = {
      name = "is-retry-allowed";
      packageName = "is-retry-allowed";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-retry-allowed/-/is-retry-allowed-1.2.0.tgz";
        sha512 = "RUbUeKwvm3XG2VYamhJL1xFktgjvPzL0Hq8C+6yrWIswDy3BIXGqCxhxkc30N9jqK311gVU137K8Ei55/zVJRg==";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha512 = "uQPm8kcs47jx38atAcWTVxyltQYoPT68y9aWYdV6yWXSyW8mzSat0TL6CiWdZeCdF3KrAvpVtnHbTv4RN+rqdQ==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha512 = "VLghIWNM6ELQzo7zwmcg0NmTVyWKYjvIeM83yjp0wRDTmUnrM678fQbcKBo6n2CJEF0szoG//ytg+TKla89ALQ==";
      };
    };
    "isurl-1.0.0" = {
      name = "isurl";
      packageName = "isurl";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isurl/-/isurl-1.0.0.tgz";
        sha512 = "1P/yWsxPlDtn7QeRD+ULKQPaIaN6yF368GZ2vDfv0AL0NwpStafjWCDDdn0k8wgFMWpVAqG7oJhxHnlud42i9w==";
      };
    };
    "jose-4.14.4" = {
      name = "jose";
      packageName = "jose";
      version = "4.14.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/jose/-/jose-4.14.4.tgz";
        sha512 = "j8GhLiKmUAh+dsFXlX1aJCbt5KMibuKb+d7j1JaOJG6s2UjX1PQlW+OKB/sD4a/5ZYF4RcmYmLSndOoU3Lt/3g==";
      };
    };
    "log-symbols-2.2.0" = {
      name = "log-symbols";
      packageName = "log-symbols";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/log-symbols/-/log-symbols-2.2.0.tgz";
        sha512 = "VeIAFslyIerEJLXHziedo2basKbMKtTw3vfn5IzG0XTjhAVEJyNHnL2p7vc+wBDSdQuUpNw3M2u6xb9QsAY5Eg==";
      };
    };
    "lowercase-keys-1.0.1" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.1.tgz";
        sha512 = "G2Lj61tXDnVFFOi8VZds+SoQjtQC3dgokKdDG2mTm1tx4m50NUHBOZSBwQQHyy0V12A0JTG4icfZQH+xPyh8VA==";
      };
    };
    "magic-string-0.30.3" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.30.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.3.tgz";
        sha512 = "B7xGbll2fG/VjP+SWg4sX3JynwIU0mjoTc6MPpKNuIvftk6u6vqhDnk1R80b8C2GBR6ywqy+1DcKBrevBg+bmw==";
      };
    };
    "make-dir-1.3.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-1.3.0.tgz";
        sha512 = "2w31R7SJtieJJnQtGc7RVL2StM2vGYVfqUOvUDxH6bC6aJTxPxTF0GnIgCyu7tjockiUWAYQRbxa7vKn34s5sQ==";
      };
    };
    "mimic-fn-1.2.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-1.2.0.tgz";
        sha512 = "jf84uxzwiuiIVKiOLpfYk7N46TSy8ubTonmneY9vrpHNAnp0QBt2BxWV9dO3/j+BoVAb+a5G6YDPW3M5HOdMWQ==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "mkdirp-0.5.6" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.6.tgz";
        sha512 = "FP+p8RB8OWpF3YZBCrP5gtADmtXApB5AMLn+vdyA+PyxCjrCs00mjyUozssO33cwDeT3wNGdLxJ5M//YqtHAJw==";
      };
    };
    "moment-2.29.4" = {
      name = "moment";
      packageName = "moment";
      version = "2.29.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.29.4.tgz";
        sha512 = "5LC9SOxjSc2HF6vO2CyuTDNivEdoz2IvyJJGj6X8DJ0eFyfszE0QiEd+iXmBvUP3WHxSjFH/vIsA0EN00cgr8w==";
      };
    };
    "moment-timezone-0.5.43" = {
      name = "moment-timezone";
      packageName = "moment-timezone";
      version = "0.5.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment-timezone/-/moment-timezone-0.5.43.tgz";
        sha512 = "72j3aNyuIsDxdF1i7CEgV2FfxM1r6aaqJyLB2vwb33mXYyoyLly+F1zbWqhA3/bVIoJ4szlUoMbUnVdid32NUQ==";
      };
    };
    "nanoid-3.3.6" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.6.tgz";
        sha512 = "BGcqMMJuToF7i1rt+2PWSNVnWIkGCU78jBG3RxO/bZlnZPK2Cmi2QaffxGO/2RvWi9sL+FAiRiXMgsyxQ1DIDA==";
      };
    };
    "ncp-2.0.0" = {
      name = "ncp";
      packageName = "ncp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ncp/-/ncp-2.0.0.tgz";
        sha512 = "zIdGUrPRFTUELUvr3Gmc7KZ2Sw/h1PiVM0Af/oHB6zgnV1ikqSfRk+TOufi79aHYCW3NiOXmr1BP5nWbzojLaA==";
      };
    };
    "npm-conf-1.1.3" = {
      name = "npm-conf";
      packageName = "npm-conf";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-conf/-/npm-conf-1.1.3.tgz";
        sha512 = "Yic4bZHJOt9RCFbRP3GgpqhScOY4HH3V2P8yBj6CeYq118Qr+BLXqT2JvpJ00mryLESpgOxf5XlFv4ZjXxLScw==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "onetime-2.0.1" = {
      name = "onetime";
      packageName = "onetime";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-2.0.1.tgz";
        sha512 = "oyyPpiMaKARvvcgip+JV+7zci5L8D1W9RZIz2l1o08AM3pfspitVWnPt3mzHcBPp12oYMTy0pqrFs/C+m3EwsQ==";
      };
    };
    "ora-3.4.0" = {
      name = "ora";
      packageName = "ora";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ora/-/ora-3.4.0.tgz";
        sha512 = "eNwHudNbO1folBP3JsZ19v9azXWtQZjICdr3Q0TDPIaeBQ3mXLrh54wM+er0+hSp+dWKf+Z8KM58CYzEyIYxYg==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "pend-1.2.0" = {
      name = "pend";
      packageName = "pend";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pend/-/pend-1.2.0.tgz";
        sha512 = "F3asv42UuXchdzt+xXqfW1OGlVBe+mxa2mqI0pg5yAHZPvFmY3Y6drSf/GQ1A86WgWEN9Kzh/WrgKa6iGcHXLg==";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha512 = "udgsAY+fTnvv7kI7aaxbqwWNb0AHiB0qBO89PZKPkoTmGOgdbrHDKD+0B2X4uTfJ/FT1R09r9gTsjUjNJotuog==";
      };
    };
    "pify-3.0.0" = {
      name = "pify";
      packageName = "pify";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-3.0.0.tgz";
        sha512 = "C3FsVNH1udSEX48gGX1xfvwTWfsYWj5U+8/uK15BGzIGrKoUpghX8hWZwa/OFnakBiiVNmBvemTJR5mcy7iPcg==";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha512 = "MnUuEycAemtSaeFSjXKW/aroV7akBbY+Sv+RkyqFjgAe73F+MR0TBWKBRDkmfWq/HiFmdavfZ1G7h4SPZXaCSg==";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha512 = "0Gni6D4UcLTbv9c57DfxDGdr41XfgUjqWZu492f0cIGr16zDU06BWP/RAEvOuo7CQ0CNjHaLlM59YJJFm3NWlw==";
      };
    };
    "postcss-8.4.29" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.4.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.4.29.tgz";
        sha512 = "cbI+jaqIeu/VGqXEarWkRCCffhjgXc0qjBtXpqJhTBohMUjUQnbBr0xqX3vEKudc4iviTewcJo5ajcec5+wdJw==";
      };
    };
    "prepend-http-1.0.4" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-1.0.4.tgz";
        sha512 = "PhmXi5XmoyKw1Un4E+opM2KcsJInDvKyuOumcjjw3waw86ZNjHwVUOOWLc4bCzLdcKNaWBH9e99sbWzDQsVaYg==";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha512 = "vtK/94akxsTMhe0/cbfpR+syPuszcuwhqVjJq26CuNDgFGj682oRBXOP5MJpv2r7JtE8MsiepGIqvvOTBwn2vA==";
      };
    };
    "qrcode.vue-3.4.1" = {
      name = "qrcode.vue";
      packageName = "qrcode.vue";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qrcode.vue/-/qrcode.vue-3.4.1.tgz";
        sha512 = "wq/zHsifH4FJ1GXQi8/wNxD1KfQkckIpjK1KPTc/qwYU5/Bkd4me0w4xZSg6EXk6xLBkVDE0zxVagewv5EMAVA==";
      };
    };
    "readable-stream-2.3.8" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.8.tgz";
        sha512 = "8p0AUk4XODgIewSi0l8Epjs+EVnWiK7NoDIEGU0HhE7+ZyY8D1IMY7odu5lRrFXGg71L15KG8QrPmum45RTtdA==";
      };
    };
    "restore-cursor-2.0.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-2.0.0.tgz";
        sha512 = "6IzJLuGi4+R14vwagDHX+JrXmPVtPpn4mffDJ1UdR7/Edm87fl6yi8mMBIVvFtJaNTUvjughmW4hwLhRG7gC1Q==";
      };
    };
    "rimraf-2.7.1" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz";
        sha512 = "uWjbaKIK3T1OSVptzX7Nl6PvQ3qAGtKEtVRjRuazjfL3Bx5eI409VZSqgND+4UNnmzLVdPj9FqFJNPqBZFve4w==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "seek-bzip-1.0.6" = {
      name = "seek-bzip";
      packageName = "seek-bzip";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/seek-bzip/-/seek-bzip-1.0.6.tgz";
        sha512 = "e1QtP3YL5tWww8uKaOCQ18UxIT2laNBXHjV/S2WYCiK4udiv8lkG89KRIoCjUagnAmCBurjF4zEVX2ByBbnCjQ==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "source-map-js-1.0.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.2.tgz";
        sha512 = "R0XvVJ9WusLiqTCEiGCmICCMplcCkIwwR11mOSD9CR5u+IXYdiseeEuXCVAjS54zqwkLcPNnmU4OeJ6tUrWhDw==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "strip-ansi-5.2.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-5.2.0.tgz";
        sha512 = "DuRs1gKbBqsMKIZlrffwlug8MHkcnpjs5VPmL1PAh+mA30U0DTotfDZ0d2UUsXpPmPmMMJ6W773MaA3J+lbiWA==";
      };
    };
    "strip-dirs-2.1.0" = {
      name = "strip-dirs";
      packageName = "strip-dirs";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-dirs/-/strip-dirs-2.1.0.tgz";
        sha512 = "JOCxOeKLm2CAS73y/U4ZeZPTkE+gNVCzKt7Eox84Iej1LT/2pTWYpZKJuxwQpvX1LiZb1xokNR7RLfuBAa7T3g==";
      };
    };
    "strip-outer-1.0.1" = {
      name = "strip-outer";
      packageName = "strip-outer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-outer/-/strip-outer-1.0.1.tgz";
        sha512 = "k55yxKHwaXnpYGsOzg4Vl8+tDrWylxDEpknGjhTiZB8dFRU5rTo9CAzeycivxV3s+zlTKwrs6WxMxR95n26kwg==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "tar-stream-1.6.2" = {
      name = "tar-stream";
      packageName = "tar-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar-stream/-/tar-stream-1.6.2.tgz";
        sha512 = "rzS0heiNf8Xn7/mpdSVVSMAWAoy9bfb1WOTYC78Z0UQKeKa/CWS8FOq0lKGNa8DWKAn9gxjCvMLYc5PGXYlK2A==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha512 = "w89qg7PI8wAdvX60bMDP+bFoD5Dvhm9oLheFp5O4a2QF0cSBGsBX4qZmadPMvVqlLJBBci+WqGGOAPvcDeNSVg==";
      };
    };
    "timed-out-4.0.1" = {
      name = "timed-out";
      packageName = "timed-out";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/timed-out/-/timed-out-4.0.1.tgz";
        sha512 = "G7r3AhovYtr5YKOWQkta8RKAPb+J9IsO4uVmzjl8AZwfhs8UcUwTiD6gcJYSgOtzyjvQKrKYn41syHbUWMkafA==";
      };
    };
    "to-buffer-1.1.1" = {
      name = "to-buffer";
      packageName = "to-buffer";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-buffer/-/to-buffer-1.1.1.tgz";
        sha512 = "lx9B5iv7msuFYE3dytT+KE5tap+rNYw+K4jVkb9R/asAb+pbBSM17jtunHplhBe6RRJdZx3Pn2Jph24O32mOVg==";
      };
    };
    "trim-repeated-1.0.0" = {
      name = "trim-repeated";
      packageName = "trim-repeated";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim-repeated/-/trim-repeated-1.0.0.tgz";
        sha512 = "pkonvlKk8/ZuR0D5tLW8ljt5I8kmxp2XKymhepUeOdCEfKpZaktSArkLHZt76OB1ZvO9bssUsDty4SWhLvZpLg==";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha512 = "McnNiV1l8RYeY8tBgEpuodCC1mLUdbSN+CYBL7kJsJNInOP8UjDDEwdk6Mw60vdLLrr5NHKZhMAOSrR2NZuQ+w==";
      };
    };
    "unbzip2-stream-1.4.3" = {
      name = "unbzip2-stream";
      packageName = "unbzip2-stream";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unbzip2-stream/-/unbzip2-stream-1.4.3.tgz";
        sha512 = "mlExGW4w71ebDJviH16lQLtZS32VKqsSfk80GCfUlwT/4/hNRFsoscrF/c++9xinkMzECL1uL9DDwXqFWkruPg==";
      };
    };
    "universal-base64-2.1.0" = {
      name = "universal-base64";
      packageName = "universal-base64";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-base64/-/universal-base64-2.1.0.tgz";
        sha512 = "WeOkACVnIXJZr/qlv7++Rl1zuZOHN96v2yS5oleUuv8eJOs5j9M5U3xQEIoWqn1OzIuIcgw0fswxWnUVGDfW6g==";
      };
    };
    "universal-base64url-1.1.0" = {
      name = "universal-base64url";
      packageName = "universal-base64url";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-base64url/-/universal-base64url-1.1.0.tgz";
        sha512 = "qWv2+8KCaAWdpqqXwU8W0Yj9pflYDXP37/a3kec6Y4Je7bYzgIfxEVRjZWeLR67be7iot1lGCy5Nuo+xB0fojA==";
      };
    };
    "unzip-response-2.0.1" = {
      name = "unzip-response";
      packageName = "unzip-response";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unzip-response/-/unzip-response-2.0.1.tgz";
        sha512 = "N0XH6lqDtFH84JxptQoZYmloF4nzrQqqrAymNj+/gW60AO2AZgOcf4O/nUXJcYfyQkqvMo9lSupBZmmgvuVXlw==";
      };
    };
    "url-parse-lax-1.0.0" = {
      name = "url-parse-lax";
      packageName = "url-parse-lax";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse-lax/-/url-parse-lax-1.0.0.tgz";
        sha512 = "BVA4lR5PIviy2PMseNd2jbFQ+jwSwQGdJejf5ctd1rEXt0Ypd7yanUK9+lYechVlN5VaTJGsu2U/3MDDu6KgBA==";
      };
    };
    "url-to-options-1.0.1" = {
      name = "url-to-options";
      packageName = "url-to-options";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-to-options/-/url-to-options-1.0.1.tgz";
        sha512 = "0kQLIzG4fdk/G5NONku64rSH/x32NOA39LVQqlK8Le6lvTF6GGRJpqaQFGgU+CLwySIqBSMdwYM0sYcW9f6P4A==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "vue-3.3.4" = {
      name = "vue";
      packageName = "vue";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue/-/vue-3.3.4.tgz";
        sha512 = "VTyEYn3yvIeY1Py0WaYGZsXnz3y5UnGi62GjVEqvEGPl6nxbOrCXbVOTQWBEJUqAyTUk2uJ5JLVnYJ6ZzGbrSw==";
      };
    };
    "wcwidth-1.0.1" = {
      name = "wcwidth";
      packageName = "wcwidth";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wcwidth/-/wcwidth-1.0.1.tgz";
        sha512 = "XHPEwS0q6TaxcvG85+8EYkbiCux2XtWG2mkc47Ng2A77BQu9+DqIOJldST4HgPkuea7dvKSj5VgX3P1d4rW8Tg==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
    "yauzl-2.10.0" = {
      name = "yauzl";
      packageName = "yauzl";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yauzl/-/yauzl-2.10.0.tgz";
        sha512 = "p4a9I6X6nu6IhoGmBqAcbJy1mlC4j27vEPZX9F4L4/vZT3Lyq1VkFHw/V/PUcB9Buo+DG3iHkT0x3Qya58zc3g==";
      };
    };
  };
  args = {
    name = "register";
    packageName = "register";
    version = "1.2.2";
    src = ./.;
    dependencies = [
      sources."@babel/parser-7.22.14"
      sources."@jridgewell/sourcemap-codec-1.4.15"
      sources."@tauri-apps/api-1.4.0"
      sources."@vue/compiler-core-3.3.4"
      sources."@vue/compiler-dom-3.3.4"
      sources."@vue/compiler-sfc-3.3.4"
      sources."@vue/compiler-ssr-3.3.4"
      sources."@vue/reactivity-3.3.4"
      sources."@vue/reactivity-transform-3.3.4"
      sources."@vue/runtime-core-3.3.4"
      sources."@vue/runtime-dom-3.3.4"
      sources."@vue/server-renderer-3.3.4"
      sources."@vue/shared-3.3.4"
      sources."ansi-regex-4.1.1"
      sources."ansi-styles-3.2.1"
      sources."axios-0.23.0"
      sources."balanced-match-1.0.2"
      sources."base64-js-1.5.1"
      sources."bl-1.2.3"
      sources."brace-expansion-1.1.11"
      sources."buffer-5.7.1"
      sources."buffer-alloc-1.2.0"
      sources."buffer-alloc-unsafe-1.1.0"
      sources."buffer-crc32-0.2.13"
      sources."buffer-fill-1.0.0"
      sources."capture-stack-trace-1.0.2"
      sources."cargo-cli-0.0.7"
      sources."caw-2.0.1"
      sources."chalk-2.4.2"
      sources."cli-cursor-2.1.0"
      sources."cli-spinners-1.3.1"
      sources."clone-1.0.4"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."commander-2.20.3"
      sources."concat-map-0.0.1"
      sources."config-chain-1.1.13"
      sources."core-util-is-1.0.3"
      sources."create-error-class-3.0.2"
      sources."cron-1.8.2"
      sources."csstype-3.1.2"
      sources."decompress-4.2.1"
      sources."decompress-tar-4.1.1"
      (sources."decompress-tarbz2-4.1.1" // {
        dependencies = [
          sources."file-type-6.2.0"
        ];
      })
      sources."decompress-targz-4.1.1"
      (sources."decompress-unzip-4.0.1" // {
        dependencies = [
          sources."file-type-3.9.0"
          sources."get-stream-2.3.1"
        ];
      })
      sources."defaults-1.0.4"
      sources."dexie-3.2.4"
      sources."download-5.0.3"
      sources."download-git-repo-1.1.0"
      sources."duplexer3-0.1.5"
      sources."end-of-stream-1.4.4"
      sources."escape-string-regexp-1.0.5"
      sources."estree-walker-2.0.2"
      sources."fd-slicer-1.1.0"
      sources."file-type-5.2.0"
      sources."filename-reserved-regex-2.0.0"
      sources."filenamify-2.1.0"
      sources."follow-redirects-1.15.2"
      sources."fs-constants-1.0.0"
      sources."fs.realpath-1.0.0"
      sources."get-proxy-2.1.0"
      sources."get-stream-3.0.0"
      sources."git-clone-0.1.0"
      sources."glob-7.2.3"
      sources."got-6.7.1"
      sources."graceful-fs-4.2.11"
      sources."has-flag-3.0.0"
      sources."has-symbol-support-x-1.4.2"
      sources."has-to-string-tag-x-1.4.1"
      sources."ieee754-1.2.1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ini-1.3.8"
      sources."is-natural-number-4.0.1"
      sources."is-object-1.0.2"
      sources."is-redirect-1.0.0"
      sources."is-retry-allowed-1.2.0"
      sources."is-stream-1.1.0"
      sources."isarray-1.0.0"
      sources."isurl-1.0.0"
      sources."jose-4.14.4"
      sources."log-symbols-2.2.0"
      sources."lowercase-keys-1.0.1"
      sources."magic-string-0.30.3"
      (sources."make-dir-1.3.0" // {
        dependencies = [
          sources."pify-3.0.0"
        ];
      })
      sources."mimic-fn-1.2.0"
      sources."minimatch-3.1.2"
      sources."minimist-1.2.8"
      sources."mkdirp-0.5.6"
      sources."moment-2.29.4"
      sources."moment-timezone-0.5.43"
      sources."nanoid-3.3.6"
      sources."ncp-2.0.0"
      (sources."npm-conf-1.1.3" // {
        dependencies = [
          sources."pify-3.0.0"
        ];
      })
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."onetime-2.0.1"
      (sources."ora-3.4.0" // {
        dependencies = [
          sources."cli-spinners-2.9.0"
        ];
      })
      sources."path-is-absolute-1.0.1"
      sources."pend-1.2.0"
      sources."picocolors-1.0.0"
      sources."pify-2.3.0"
      sources."pinkie-2.0.4"
      sources."pinkie-promise-2.0.1"
      sources."postcss-8.4.29"
      sources."prepend-http-1.0.4"
      sources."process-nextick-args-2.0.1"
      sources."proto-list-1.2.4"
      sources."qrcode.vue-3.4.1"
      (sources."readable-stream-2.3.8" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."restore-cursor-2.0.0"
      sources."rimraf-2.7.1"
      sources."safe-buffer-5.2.1"
      sources."seek-bzip-1.0.6"
      sources."signal-exit-3.0.7"
      sources."source-map-js-1.0.2"
      (sources."string_decoder-1.1.1" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."strip-ansi-5.2.0"
      sources."strip-dirs-2.1.0"
      sources."strip-outer-1.0.1"
      sources."supports-color-5.5.0"
      sources."tar-stream-1.6.2"
      sources."through-2.3.8"
      sources."timed-out-4.0.1"
      sources."to-buffer-1.1.1"
      sources."trim-repeated-1.0.0"
      sources."tunnel-agent-0.6.0"
      sources."unbzip2-stream-1.4.3"
      sources."universal-base64-2.1.0"
      sources."universal-base64url-1.1.0"
      sources."unzip-response-2.0.1"
      sources."url-parse-lax-1.0.0"
      sources."url-to-options-1.0.1"
      sources."util-deprecate-1.0.2"
      sources."vue-3.3.4"
      sources."wcwidth-1.0.1"
      sources."wrappy-1.0.2"
      sources."xtend-4.0.2"
      sources."yauzl-2.10.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
