/* tslint:disable */
/* eslint-disable */
/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Postal } from "./postal";

/**
 * an address
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {Postal}
     * @memberof Address
     */
    postal: Postal;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    phone: any;
}
