/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * body of addItem request
 */
export interface AddReceiptItemBody { 
    /**
     * the receipt code (size 20) where the item belongs
     */
    receiptcode?: string;
    /**
     * or if a new receipt should be opened need the register ID
     */
    registerId?: string;
    customerId?: number;
    itemCode: string;
    /**
     * quantity or item to add
     */
    qty?: number;
    /**
     * nature of receipt (see enum receipt_type)
     */
    receiptType?: string;
}