/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ButtonType } from './buttonType';

/**
 * a button is a freely definable function or article on the register screen
 */
export interface Button { 
    id: number;
    name: string;
    type: ButtonType;
    /**
     * product code
     */
    article: string;
    /**
     * if type is 'article', group adds the button to the button group if type is 'group' this button holds a group of buttons 
     */
    group: number;
}