/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * function type of button
 */
export type ButtonType = 'article' | 'group' | 'function';

export const ButtonType = {
    Article: 'article' as ButtonType,
    Group: 'group' as ButtonType,
    Function: 'function' as ButtonType
};