/* tslint:disable */
/* eslint-disable */
/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * all data specific to the company
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * the company ID
     * @type {number}
     * @memberof Company
     */
    id: any;
    /**
     * the company name
     * @type {string}
     * @memberof Company
     */
    name: any;
    /**
     * array with address lines
     * @type {Array&lt;string&gt;}
     * @memberof Company
     */
    address: any;
    /**
     * 
     * @type {RksvCred}
     * @memberof Company
     */
    rksvCred: any;
    /**
     * RKSV signing root certificate DER format BASE64 encoded
     * @type {string}
     * @memberof Company
     */
    rksvRootCert: any;
}
