/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Timestamp } from './timestamp';

/**
 * a credit account for a customer
 */
export interface CreditAccountLine { 
    /**
     * the customer ID
     */
    customer_id: number;
    timestamp?: Timestamp;
    /**
     * the receipt code
     */
    receiptcode: string;
    /**
     * the line amount in cents
     */
    amount: number;
    /**
     * account line information eg. deposit from paypal or debit for invoice nr
     */
    text: string;
}