/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { Address } from './address';

 /**
  * a customer has a name and address and a credit account
  */
 export interface Customer { 
     /**
      * the customer id
      */
     id: number;
     /**
      * the name of the customer
      */
     name: string;
     address: Address;
     /**
      * the uid of the rfid key
      */
     keyUid: number;

     type?: string;
 }