/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * type of payment
 */
export type PaymentType = 'ec' | 'bluecode' | 'cash' | 'bill' | 'rksv' | 'credit';

export const PaymentType = {
    Ec: 'ec' as PaymentType,
    Bluecode: 'bluecode' as PaymentType,
    Credit: 'credit' as PaymentType,
    Cash: 'cash' as PaymentType,
    Bill: 'bill' as PaymentType,
    Rksv: 'rksv' as PaymentType
};