/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * status of payment
 */
export type PaymentStatus = 'success' | 'abort' | 'pending';

export const PaymentStatus = {
    Success: 'success' as PaymentStatus,
    Abort: 'abort' as PaymentStatus,
    Pending: 'pending' as PaymentStatus
};