/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthoriseResponseData } from '../pt/authoriseResponseData';
import { PaymentCustomerAccount } from './paymentCustomerAccount';
import { PaymentStatus } from './paymentStatus';
import { PaymentType } from './paymentType';
import { Timestamp } from './timestamp';

export interface Payment { 
    starttime: Timestamp;
    /**
     * receipt code
     */
    receipt_code: string;
    /**
     * the payment amount in cent
     */
    amount: number;
    type: PaymentType;
    status: PaymentStatus;
    /**
     * DEPRECATED a json object with payment specific data
     */
    data: string;
    ptdata?: AuthoriseResponseData;
    customer_account?: PaymentCustomerAccount;
    /**
     * signed jwt
     */
    rksv_jwt?: string;
    /**
     * rksv short code for uri
     */
    rksv_code?: string;
    /**
     * the registers salescounter for RKSV in cent
     */
    salescounter?: number;
}