/* tslint:disable */
/* eslint-disable */
/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Postal
 */
export interface Postal {
    /**
     * 
     * @type {string}
     * @memberof Postal
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof Postal
     */
    street: any;
    /**
     * 
     * @type {string}
     * @memberof Postal
     */
    zip: any;
    /**
     * 
     * @type {string}
     * @memberof Postal
     */
    city: any;
}
