/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * a product is a fixed schema of a sellable item
 */
export interface Product { 
    /**
     * product code (EAN)
     */
    code: string;
    /**
     * short name of product
     */
    name: string;
    /**
     * the text description of the product
     */
    text: string;
    /**
     * base price in net EUR cent
     */
    price: number;
    /**
     * purchase price in net EUR cent
     */
    purchase: number;
    /**
     * tax group id
     */
    taxGroupId: number;
}