/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Discount } from './discount';
import { Product } from './product';
import { TaxType } from './taxType';

/**
 * the single items of a receipt
 */
export interface ReceiptItem { 
    /**
     * the receipt code where the item belongs
     */
    receiptCode: string;
    product: Product;
    qty?: number;
    /**
     * the product price in cent at that moment in time
     */
    price: number;
    /**
     * the tax rate in percent at that moment in time
     */
    taxRate: number;
    taxType: TaxType;
    discount?: Discount;
    /**
     * line total (qty * price) in cent with discount accounted
     */
    total: number;
}