/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * type of receipt (rksv type)
 */
export type ReceiptType = 'start' | 'standard' | 'storno' | 'training' | 'zero';

export const ReceiptType = {
    Start: 'start' as ReceiptType,
    Standard: 'standard' as ReceiptType,
    Storno: 'storno' as ReceiptType,
    Training: 'training' as ReceiptType,
    Zero: 'zero' as ReceiptType
};