/* tslint:disable */
/* eslint-disable */
/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * the single items of a receipt
 * @export
 * @interface ReceiptItem
 */
export interface ReceiptItem {
    /**
     * the receipt code where the item belongs
     * @type {string}
     * @memberof ReceiptItem
     */
    receiptCode: any;
    /**
     * 
     * @type {Product}
     * @memberof ReceiptItem
     */
    product: any;
    /**
     * 
     * @type {number}
     * @memberof ReceiptItem
     */
    qty?: any;
    /**
     * the product price in cent at that moment in time
     * @type {number}
     * @memberof ReceiptItem
     */
    price: any;
    /**
     * the tax rate in percent at that moment in time
     * @type {number}
     * @memberof ReceiptItem
     */
    taxRate: any;
    /**
     * 
     * @type {TaxType}
     * @memberof ReceiptItem
     */
    taxType: any;
    /**
     * 
     * @type {Discount}
     * @memberof ReceiptItem
     */
    discount?: any;
    /**
     * line total (qty * price) in cent with discount accounted
     * @type {number}
     * @memberof ReceiptItem
     */
    total: any;
}
