/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * the state of the receipt
 */
export type ReceiptStatus = 'open' | 'payed' | 'cancelled' | 'parked';

export const ReceiptStatus = {
    Open: 'open' as ReceiptStatus,
    Payed: 'payed' as ReceiptStatus,
    Cancelled: 'cancelled' as ReceiptStatus,
    Parked: 'parked' as ReceiptStatus
};