/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RegisterState } from './registerState';

/**
 * a register entity
 */
export interface Register { 
    /**
     * KassenID - Aufbau: 5stellige Gemeindekennziffer  + 1stelle als Kassennummer in der Gemeinde
     */
    id: string;
    /**
     * the registers name
     */
    name: string;
    /**
     * the id of the company that the register is associated to
     */
    company_id: number;
    /**
     * the id of the user that the register is associated to
     */
    user_id: number;
    /**
     * the storage where the register is located
     */
    storage_id: number;
    /**
     * on time TAN for auth init
     */
    tan?: string;
    /**
     * the prime sign key ID for this register
     */
    certKeyId: string;
    /**
     * the prime cert serial nr for this register
     */
    certSerial: string;
    /**
     * the public key from the key pair is used to verify the identity of the register on every request using JWT
     */
    publicKey?: string;
    /**
     * the base64 encoded 32 byte long RSA key for rksv sales counter encryption
     */
    salescounterKey: string;
    /**
     * true if successful registration at FinanzOnline stated
     */
    fon: boolean;
    state: RegisterState;
    /**
     * the ID of the register config assigned to the register
     */
    config_id: number;
}