/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * state of the register
 */
export type RegisterState = 'active' | 'registered' | 'created' | 'deactivated';

export const RegisterState = {
    Active: 'active' as RegisterState,
    Registered: 'registered' as RegisterState,
    Created: 'created' as RegisterState,
    Deactivated: 'deactivated' as RegisterState
};