/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RegisterDevices } from './registerDevices';
import { Timestamp } from './timestamp';

/**
 * the register status e.g. heart beat, new errors, etc.
 */
export interface RegisterStatus { 
    registerId: string;
    timestamp?: Timestamp;
    devices: RegisterDevices;
    error?: string;
}