/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Tax { 
    /**
     * tax rate in percent
     */
    rate: number;
    /**
     * tax amount included in cent
     */
    amount: number;
}