/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Timestamp } from './timestamp';

/**
 * a single percentage rate for a specific  tax group with a tax type with a \"valid from\" date
 */
export interface TaxItem { 
    /**
     * tax rate in percentage
     */
    rate: number;
    validFrom: Timestamp;
}