/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * type of tax
 */
export type TaxType = 'normal' | 'reduced1' | 'reduced2' | 'zero' | 'special';

export const TaxType = {
    Normal: 'normal' as TaxType,
    Reduced1: 'reduced1' as TaxType,
    Reduced2: 'reduced2' as TaxType,
    Zero: 'zero' as TaxType,
    Special: 'special' as TaxType
};