/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Tax } from './tax';

export interface TotalAmounts { 
    /**
     * total price in cent
     */
    price?: number;
    /**
     * total discount in cent
     */
    discountAmount?: number;
    /**
     * list of all different taxes included
     */
    taxes?: Array<Tax>;
}