/**
 * MMS
 * Merchandise Management System -  API first approach
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User { 
    id: number;
    type: User.TypeEnum;
    name: string;
    groups: Array<number>;
    publicKey?: string;
    tan?: string;
    state: User.StateEnum;
    registerId?: string;
}
export namespace User {
    export type TypeEnum = 'register' | 'customer' | 'office' | 'admin';
    export const TypeEnum = {
        Register: 'register' as TypeEnum,
        Customer: 'customer' as TypeEnum,
        Office: 'office' as TypeEnum,
        Admin: 'admin' as TypeEnum
    };
    export type StateEnum = 'active' | 'created' | 'inactive';
    export const StateEnum = {
        Active: 'active' as StateEnum,
        Created: 'created' as StateEnum,
        Inactive: 'inactive' as StateEnum
    };
}