/**
 * PTAPI
 * Payment Device API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Card { 
    sequenceNr: number;
    type: number;
    name: string;
    /**
     * YYMM
     */
    expiry: string;
    panEfId: string;
}

export interface AuthoriseResponseData { 
    amount: number;
    currency: number;
    timestamp: string;
    terminalId: string;
    vuNr: string;
    receiptNr: number;
    turnoverNr: number;
    cardTech: number;
    aid: string;
    emvCustomer: string;
    emvMerchant: string;
    info: string;
    /**
     * EMV-print-data (merchant-receipt)
     */
    crypto: string;
    card: Card;
}