/**
 * PTAPI
 * Payment Device API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthoriseResponse } from './authoriseResponse';

export interface AuthCompletionResponse { 
    status: number;
    message: string;
    transaction?: AuthoriseResponse;
}