/**
 * PTAPI
 * Payment Device API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PtResult = 'pending' | 'success' | 'timeout' | 'need_end_of_day' | 'abort';

export const PtResult = {
    Pending: 'pending' as PtResult,
    Success: 'success' as PtResult,
    Timeout: 'timeout' as PtResult,
    NeedEndOfDay: 'need_end_of_day' as PtResult,
    Abort: 'abort' as PtResult
};